//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public System.DateTime Date { get; set; }
        public string Address { get; set; }
        public int TeacherId { get; set; }
        public int Courseid { get; set; }
        public int Classid { get; set; }
    
        public virtual classs classs { get; set; }
        public virtual Course Course { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
